// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBecaZnr0yPFDmDwsfa9jjStfygXQ55UQ8',
    appId: '1:1086435698084:android:2eabe060922c86de344d31',
    messagingSenderId: '1086435698084',
    projectId: 'chat-zxc',
    storageBucket: 'chat-zxc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkxji0u7y2PQe-Zw0QYcAGLYr-0k5GqFU',
    appId: '1:1086435698084:ios:a395a0cd81ab8d24344d31',
    messagingSenderId: '1086435698084',
    projectId: 'chat-zxc',
    storageBucket: 'chat-zxc.firebasestorage.app',
    iosBundleId: 'com.zxc.chatZxc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkxji0u7y2PQe-Zw0QYcAGLYr-0k5GqFU',
    appId: '1:1086435698084:ios:a395a0cd81ab8d24344d31',
    messagingSenderId: '1086435698084',
    projectId: 'chat-zxc',
    storageBucket: 'chat-zxc.firebasestorage.app',
    iosBundleId: 'com.zxc.chatZxc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG9E37HeDMhlQQ1sYO-t6SoldtdYGDA4Q',
    appId: '1:1086435698084:web:9a0e8cf0a3bc2c25344d31',
    messagingSenderId: '1086435698084',
    projectId: 'chat-zxc',
    authDomain: 'chat-zxc.firebaseapp.com',
    storageBucket: 'chat-zxc.firebasestorage.app',
    measurementId: 'G-28G3X4ECHW',
  );
}
